### ISSUE TITLE
Log in  Issue

### ISSUE THREAD

**Issue by msjagan** [ignitedcms/ignitedcms-pro#1]
While installing IgnitedCMS for first time, after giving all inputs correctly. It is keep asking to enter password for the username "**admin**".

**Comment by ignitedcms** [comment]
I think this could be a PHP version issue, can you try using PHP version 5.6 and see if that works until I find a fix?

**Comment by msjagan** [comment]
Okay 
I will check on 5.6 version. If doesn't work, then I will also try to find solution to this issue.
